width: 800
height: 800
luminosity-label: '%1$.2f fb^{-1} (13 TeV)'
experiment: "CMS"
extra-label: "Preliminary"

#root: '/home/fynu/bfrancois/scratch/framework/MIS_prod_data/CMSSW_7_6_5/src/cp3_llbb/HHTools/histFactory_hh/MIS_RUNII_firstRound/condor/output/'
#root: '/home/fynu/bfrancois/scratch/framework/MIS_prod_data/CMSSW_7_6_5/src/cp3_llbb/HHTools/histFactory_hh/singleTopWeigt_v1/condor/output/'
#root: '/home/fynu/bfrancois/scratch/framework/MIS_prod_data/CMSSW_7_6_5/src/cp3_llbb/HHTools/histFactory_hh/5f_singleTopWeigt_v0_checkPermutation_noAddBjetBoost_moreTW/condor/output/'

#root: '/home/fynu/bfrancois/scratch/framework/MIS_prod_data/CMSSW_7_6_5/src/cp3_llbb/HHTools/histFactory_hh/weightPlot_v3/condor/output/'
#root: '/home/fynu/bfrancois/scratch/framework/MIS_prod_data/CMSSW_7_6_5/src/cp3_llbb/HHTools/histFactory_hh/combinedArcTan/condor/output/'
root: '/home/fynu/bfrancois/scratch/framework/MIS_prod_data/CMSSW_7_6_5/src/cp3_llbb/HHTools/histFactory_hh/weightPlot_btagTight_and_ZeroResults/condor/output/'

#root: '/home/fynu/bfrancois/scratch/framework/MIS_prod_data/CMSSW_7_6_5/src/cp3_llbb/HHTools/histFactory_hh/firstTTbarAndZZWeights/condor/output/'
#root: '/home/fynu/bfrancois/scratch/framework/MIS_prod_data/CMSSW_7_6_5/src/cp3_llbb/HHTools/histFactory_hh/ttWeight_noTF_NWAtrue_more/condor/output/'
#root: '/home/fynu/bfrancois/scratch/framework/MIS_prod_data/CMSSW_7_6_5/src/cp3_llbb/HHTools/histFactory_hh/refix_ttweights/condor/output/'
#root: '/home/fynu/bfrancois/scratch/framework/MIS_prod_data/CMSSW_7_6_5/src/cp3_llbb/HHTools/histFactory_hh/16_10_13_momInHistFactory_reretry/condor/output/'
#root: '/home/fynu/bfrancois/scratch/framework/MIS_prod_data/CMSSW_7_6_5/src/cp3_llbb/HHTools/histFactory_hh/checkTFEtaBinnedInterest/condor/output/'
#root: '/home/fynu/swertz/scratch/CMSSW_7_6_3_patch2/src/cp3_llbb/HHTools/condor/160624_new2Dbinnings_0/condor/output/'

luminosity: 2300  # according to brilcalc 
luminosity-error: 0.
blinded-range-fill-color: "16" #"#29556270"
blinded-range-fill-style: 3004

yields-table-align: v
