width: 800
height: 800
luminosity-label: '%1$.2f fb^{-1} (13 TeV)'
experiment: "CMS"
extra-label: "Preliminary"

# NTUPLE
#root: '/home/fynu/bfrancois/scratch/framework/oct2015/CMSSW_7_4_15/src/cp3_llbb/HHTools/histFactory_hh/76_mjjStudy/condor/output/'
# SKIM
#root: '/home/fynu/bfrancois/scratch/framework/oct2015/CMSSW_7_4_15/src/cp3_llbb/CommonTools/histFactory/hists_skimmed_btagMM_bdtCut_2016_01_17/'

root: '/home/fynu/swertz/scratch/CMSSW_7_6_3_patch2/src/cp3_llbb/HHTools/condor/160525_0/condor/output/'

luminosity: 2300  # according to brilcalc 
luminosity-error: 0.027
blinded-range-fill-color: "16" #"#29556270"
blinded-range-fill-style: 3004

yields-table-align: v
